// Animation names
#define CYBERMAN_ANIM_DEFAULT_ANIMATION 0
#define CYBERMAN_ANIM_DEATH3 1
#define CYBERMAN_ANIM_FALL3_6 2
#define CYBERMAN_ANIM_FIRE4_1 3
#define CYBERMAN_ANIM_FIRE6 4
#define CYBERMAN_ANIM_HIT2_1 5
#define CYBERMAN_ANIM_RUN3_5 6
#define CYBERMAN_ANIM_WALK3_6 7

#define CYBERMAN_ANIM_STAND CYBERMAN_ANIM_DEFAULT_ANIMATION
#define CYBERMAN_ANIM_DEATH CYBERMAN_ANIM_DEATH3 
#define CYBERMAN_ANIM_FALL CYBERMAN_ANIM_FALL3_6
#define CYBERMAN_ANIM_FIRE1 CYBERMAN_ANIM_FIRE4_1
#define CYBERMAN_ANIM_FIRE2 CYBERMAN_ANIM_FIRE6
#define CYBERMAN_ANIM_HIT CYBERMAN_ANIM_HIT2_1
#define CYBERMAN_ANIM_RUN CYBERMAN_ANIM_RUN3_5
#define CYBERMAN_ANIM_WALK CYBERMAN_ANIM_WALK3_6

// Color names

// Patch names

// Names of collision boxes
#define CYBERMAN_COLLISION_BOX_PART_NAME 0
#define CYBERMAN_COLLISION_BOX_DEATH 1

// Attaching position names

// Sound names
