/* Copyright (c) 2002-2012 Croteam Ltd. 
This program is free software; you can redistribute it and/or modify
it under the terms of version 2 of the GNU General Public License as published by
the Free Software Foundation


This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. */

// Animation names
#define LAVAMAN_ANIM_DEFAULTANIMATION 0
#define LAVAMAN_ANIM_ATTACK01 1
#define LAVAMAN_ANIM_ATTACK02 2
#define LAVAMAN_ANIM_ATTACK03 3
#define LAVAMAN_ANIM_ATTACK04 4
#define LAVAMAN_ANIM_ATTACK05 5
#define LAVAMAN_ANIM_ATTACK06 6
#define LAVAMAN_ANIM_DEATH01 7
#define LAVAMAN_ANIM_DEATH02 8
#define LAVAMAN_ANIM_DEATH03 9
#define LAVAMAN_ANIM_STANDBOX 10
#define LAVAMAN_ANIM_MORPHBOXUP 11
#define LAVAMAN_ANIM_MORPHBOXDOWN 12
#define LAVAMAN_ANIM_STANDPLANE 13
#define LAVAMAN_ANIM_MORPHPLANEUP 14
#define LAVAMAN_ANIM_MORPHPLANEDOWN 15
#define LAVAMAN_ANIM_RUN 16
#define LAVAMAN_ANIM_STAND 17
#define LAVAMAN_ANIM_WALK 18
#define LAVAMAN_ANIM_WOUND01 19
#define LAVAMAN_ANIM_WOUND02 20
#define LAVAMAN_ANIM_WOUND03 21

#define ELEMENTALLAVA_ANIM_IDLE LAVAMAN_ANIM_STAND
#define ELEMENTALLAVA_ANIM_STANDFIGHT LAVAMAN_ANIM_STAND
#define ELEMENTALLAVA_ANIM_STANDPLANE LAVAMAN_ANIM_STANDPLANE
#define ELEMENTALLAVA_ANIM_ATTACKLEFTHAND LAVAMAN_ANIM_ATTACK05
#define ELEMENTALLAVA_ANIM_ATTACKTWOHANDS LAVAMAN_ANIM_ATTACK02
#define ELEMENTALLAVA_ANIM_ATTACKBOSS LAVAMAN_ANIM_ATTACK05
#define ELEMENTALLAVA_ANIM_WOUND01 LAVAMAN_ANIM_WOUND01
#define ELEMENTALLAVA_ANIM_WOUND02 LAVAMAN_ANIM_WOUND02
#define ELEMENTALLAVA_ANIM_WOUND03 LAVAMAN_ANIM_WOUND03
#define ELEMENTALLAVA_ANIM_WALKBIG LAVAMAN_ANIM_WALK
#define ELEMENTALLAVA_ANIM_RUNSMALL LAVAMAN_ANIM_RUN
#define ELEMENTALLAVA_ANIM_RUNMEDIUM LAVAMAN_ANIM_WALK
#define ELEMENTALLAVA_ANIM_ANGER LAVAMAN_ANIM_ATTACK06
#define ELEMENTALLAVA_ANIM_DEATH03 LAVAMAN_ANIM_DEATH03
#define ELEMENTALLAVA_ANIM_MELTFLY LAVAMAN_ANIM_STANDBOX
#define ELEMENTALLAVA_ANIM_MELTUP LAVAMAN_ANIM_MORPHBOXUP
#define ELEMENTALLAVA_ANIM_WALKCOMPUTER LAVAMAN_ANIM_STAND

// Color names

// Patch names

// Names of collision boxes
#define ELEMENTALLAVA_COLLISION_BOX_NORMAL  0
#define ELEMENTALLAVA_COLLISION_BOX_BOX 1

// Attaching position names
#define ELEMENTALLAVA_ATTACHMENT_BODY_FLARE 0
#define ELEMENTALLAVA_ATTACHMENT_RIGHT_HAND_FLARE 1
#define ELEMENTALLAVA_ATTACHMENT_LEFT_HAND_FLARE 2

// Sound names
